apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: message-service
  name: message-service
spec:
  ports:
  - name: "21005"
    port: 21005
    targetPort: 8081
  selector:
    io.kompose.service: message-service
status:
  loadBalancer: {}
