apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: group-message-mysql
  name: group-message-mysql
spec:
  ports:
  - name: "3311"
    port: 3311
    targetPort: 3306
  selector:
    io.kompose.service: group-message-mysql
status:
  loadBalancer: {}
