apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: offline-message-service
  name: offline-message-service
spec:
  ports:
  - name: "21008"
    port: 21008
    targetPort: 8081
  selector:
    io.kompose.service: offline-message-service
status:
  loadBalancer: {}
