apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: user-relation-mysql
  name: user-relation-mysql
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: user-relation-mysql
    spec:
      containers:
      - args:
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        env:
        - name: MYSQL_DATABASE
          value: user-relation
        - name: MYSQL_ROOT_PASSWORD
          value: root
        image: mysql:5.6
        name: user-relation-mysql
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - mountPath: /etc/my.cnf
          name: user-relation-mysql-claim0
        - mountPath: /var/lib/mysql
          name: user-relation-mysql-claim1
      restartPolicy: Always
      volumes:
      - name: user-relation-mysql-claim0
        persistentVolumeClaim:
          claimName: user-relation-mysql-claim0
      - name: user-relation-mysql-claim1
        persistentVolumeClaim:
          claimName: user-relation-mysql-claim1
status: {}
